[package]
name = "my-project"
version = "0.1.0"
authors = ["raylee <rayylee@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant = { path = "restaurant"}
