[package]
name = "leak_bucket"
version = "0.1.0"
authors = ["rayylee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vmm-sys-util = "0.7"
libc = "0.2.71"
