[package]
name = "vncd"
version = "0.1.0"
authors = ["rayylee <rayylee@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vncserver = "0.2"
libc = "0.2"

[build-dependencies]
bindgen = "0.58"
